from __future__ import annotations

import argparse
import csv
import json
import sys
from datetime import datetime
from pathlib import Path

from sqlalchemy import func, select


BASE_DIR = Path(__file__).resolve().parents[1]
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from app.db.session import SessionLocal
from app.models.member import MemberAccount, MemberLevelChangeLog, MemberLevelPeriod, MemberProfile
from app.models.sync import SyncTaskLog


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Validate a member CSV sync batch result.")
    parser.add_argument("--result-file", required=True, help="Result CSV path generated by sync_members_from_point_csv.py")
    parser.add_argument("--expected-count", required=True, type=int, help="Expected row count for this batch.")
    parser.add_argument("--counts-before-file", required=True, help="JSON file containing database counts before the batch.")
    parser.add_argument("--report-file", required=True, help="JSON report output path.")
    parser.add_argument("--batch-no", type=int, help="Batch number.")
    parser.add_argument("--batch-size", type=int, help="Configured batch size.")
    parser.add_argument("--core-exit-code", type=int, default=0, help="Exit code from the core sync script.")
    return parser


def snapshot_counts() -> dict[str, int]:
    with SessionLocal() as session:
        return {
            "member_profile": int(session.scalar(select(func.count()).select_from(MemberProfile)) or 0),
            "member_account": int(session.scalar(select(func.count()).select_from(MemberAccount)) or 0),
            "member_level_change_log": int(session.scalar(select(func.count()).select_from(MemberLevelChangeLog)) or 0),
            "member_level_period": int(session.scalar(select(func.count()).select_from(MemberLevelPeriod)) or 0),
            "sync_task_log": int(session.scalar(select(func.count()).select_from(SyncTaskLog)) or 0),
        }


def read_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as fp:
        return json.load(fp)


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fp:
        json.dump(payload, fp, ensure_ascii=False, indent=2)


def summarize_result_csv(path: Path) -> dict[str, object]:
    if not path.exists():
        return {
            "exists": False,
            "row_count": 0,
            "success_count": 0,
            "failed_count": 0,
            "not_found_count": 0,
            "other_status_count": 0,
            "status_counts": {},
        }

    with path.open("r", encoding="utf-8-sig", newline="") as fp:
        rows = list(csv.DictReader(fp))

    status_counts: dict[str, int] = {}
    for row in rows:
        status = (row.get("sync_status") or "").strip() or "unknown"
        status_counts[status] = status_counts.get(status, 0) + 1

    return {
        "exists": True,
        "row_count": len(rows),
        "success_count": status_counts.get("success", 0),
        "failed_count": status_counts.get("failed", 0),
        "not_found_count": status_counts.get("not_found", 0),
        "other_status_count": sum(
            count for status, count in status_counts.items() if status not in {"success", "failed", "not_found"}
        ),
        "status_counts": status_counts,
    }


def main() -> None:
    args = build_parser().parse_args()
    result_file = Path(args.result_file).resolve()
    counts_before_file = Path(args.counts_before_file).resolve()
    report_file = Path(args.report_file).resolve()

    counts_before = read_json(counts_before_file)
    counts_after = snapshot_counts()
    counts_delta = {key: counts_after.get(key, 0) - int(counts_before.get(key, 0) or 0) for key in counts_after}

    result_summary = summarize_result_csv(result_file)
    row_count = int(result_summary["row_count"])
    success_count = int(result_summary["success_count"])
    failed_count = int(result_summary["failed_count"])
    not_found_count = int(result_summary["not_found_count"])
    other_status_count = int(result_summary["other_status_count"])
    status_total = success_count + failed_count + not_found_count + other_status_count

    file_ok = bool(result_summary["exists"])
    row_count_ok = row_count == args.expected_count
    status_total_ok = status_total == args.expected_count
    sync_log_growth_ok = counts_delta["sync_task_log"] >= args.expected_count
    completed_ok = file_ok and row_count_ok and status_total_ok and sync_log_growth_ok
    fully_successful = completed_ok and failed_count == 0
    data_growth_observed = any(counts_delta[key] > 0 for key in counts_delta if key != "sync_task_log")

    notes: list[str] = []
    if args.core_exit_code != 0 and completed_ok:
        notes.append("Core sync script exited non-zero, but validation passed. This usually indicates console encoding noise.")
    if not data_growth_observed:
        notes.append("No member table growth observed. This can still be normal for repeat batches with idempotent updates.")

    report = {
        "checked_at": datetime.now().isoformat(timespec="seconds"),
        "batch_no": args.batch_no,
        "batch_size": args.batch_size,
        "expected_count": args.expected_count,
        "core_exit_code": args.core_exit_code,
        "result_file": str(result_file),
        "counts_before_file": str(counts_before_file),
        "counts_before": counts_before,
        "counts_after": counts_after,
        "counts_delta": counts_delta,
        "result_summary": result_summary,
        "validation": {
            "file_ok": file_ok,
            "row_count_ok": row_count_ok,
            "status_total_ok": status_total_ok,
            "sync_log_growth_ok": sync_log_growth_ok,
            "completed_ok": completed_ok,
            "fully_successful": fully_successful,
            "data_growth_observed": data_growth_observed,
        },
        "notes": notes,
    }
    write_json(report_file, report)

    print(f"result_file: {result_file}")
    print(f"expected_count: {args.expected_count}")
    print(f"row_count: {row_count}")
    print(f"success_count: {success_count}")
    print(f"failed_count: {failed_count}")
    print(f"not_found_count: {not_found_count}")
    print(f"sync_task_log_delta: {counts_delta['sync_task_log']}")
    print(f"member_profile_delta: {counts_delta['member_profile']}")
    print(f"member_account_delta: {counts_delta['member_account']}")
    print(f"member_level_change_log_delta: {counts_delta['member_level_change_log']}")
    print(f"member_level_period_delta: {counts_delta['member_level_period']}")
    print(f"completed_ok: {completed_ok}")
    print(f"fully_successful: {fully_successful}")
    print(f"report_file: {report_file}")

    if fully_successful:
        raise SystemExit(0)
    if completed_ok:
        raise SystemExit(2)
    raise SystemExit(1)


if __name__ == "__main__":
    main()
